version: "3.3"

services:
  node-server:
    build: "./server"
    container_name: node-con
    command: npm start
    volumes:
      - ./server:/usr/app
    ports:
      - "4000:4000"
    # restart: always