version: "3.7"

services:
  node-server:
    build: "./server"
    container_name: node-con
    command: npm start
    volumes:
      - ./server:/usr/app
    ports:
      - "3000:3000"
    # restart: always